name: GitHub Actions Demo

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  MY_HOST: '202.29.104.46'
  COMPANY_NAME: 'CCT'

jobs:
    build-job:
      runs-on: ubuntu-latest
      env:
        FULLNAME: 'Mary Doe'
      steps:
        - run: echo ${{ vars.COMPANY_NAME }}
        - run: echo ${{ env.COMPANY_NAME }}
        - run: echo ${{ secrets.MYSQL_PASSWORD }}
        - run: echo "My host is $MY_HOST and $FULLNAME $COMPANY_NAME"
        - run: echo "Hello ${{ github.actor }} $FULLNAME"

    test-job:
      runs-on: ubuntu-latest
      needs: build-job
      steps:
        - run: echo "Repo is ${{ github.repository }} ${{ env.MY_HOST }}"

    deploy-job:
      runs-on: ubuntu-latest
      needs: test-job
      steps:
        - run: echo "deploy job to production server ${{ job.status }}"